spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:bookstore
        username: sa
        password: admin
        schema: classpath:sql/schema.sql
        initialization-mode: always
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enable: true
            path: /h2-console
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
